### ISSUE TITLE
MIDASexample not found

### ISSUE THREAD

**Issue by YMehmetKutluay** [pteridin/MIDASwrappeR#1]
I installed the MIDASwrappeR package and wanted to try running the ```getMIDASScore(MIDASexample, undirected = T)``` command. However I got the following error:

Error in getMIDASScore(MIDASexample, undirected = T) : 
  object 'MIDASexample' not found

There was nothing wrong in the installation of the package. Let me know if you require full session information, but it seems to be a case missing data file. I could be mistaken of course.

Many thanks in advance!

**Comment by pteridin** [comment]
Missed the data("MIDASexample") after loading the library. Should work now as stated in the Readme.

Please let me know if that's working for you. Thank you!

**Comment by pteridin** [comment]
And was behind an important commit. Sorry for that. Should be fixed after recompiling and using data() after loading the library. Sorry for this inconvenience.

**Comment by YMehmetKutluay** [comment]
It works perfectly now! I'll close the issue. Thank you!
